### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by brandonfang06** [agafonoff2000/SimpleMap#2]
Hi, 
I'm a newbie in c#, and I'm searching for some projects just like this.
I found your work really amazing and want to do some adaptations to show routes of a plane and locations it may visit.
But after downloading the whole project, I didn't know where to begin, and I would like to ask some questions:
1. Where to change the location just like the ".exe file" vertex, and where to decide the arcs (in which file)?
2. Should I first download the map then run the project, or simply just run it?

Looking forward to your reply, many thanx

**Comment by agafonoff2000** [comment]
You should download c# source, compile in Visual Studio and run. Map will be downloaded and cached automaticaly. You can change default location in *.config file. Vertexes (for example)are generated by random automaticaly. You should make any logic in the project you want to show any objects you have.
